hard_tabs = true
tab_spaces = 2
max_width = 100
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
format_strings = true
format_macro_matchers = true
use_try_shorthand = true
use_field_init_shorthand = true
remove_nested_parens = true
