# Copyright (c) 2025 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

[package]
name = "loom-server-weaver"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Weaver provisioning business logic for Loom"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
k8s-openapi.workspace = true
serde = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid7.workspace = true

reqwest.workspace = true

loom-common-webhook.workspace = true

loom-server-k8s.workspace = true
loom-common-secret.workspace = true

[dev-dependencies]
proptest.workspace = true
